package oracledialect

import (
	"database/sql"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect"
	"github.com/uptrace/bun/dialect/feature"
	"github.com/uptrace/bun/dialect/sqltype"
	"github.com/uptrace/bun/schema"
)

func init() {
	if Version() != bun.Version() {
		panic(fmt.Errorf("oracledialect and Bun must have the same version: v%s != v%s",
			Version(), bun.Version()))
	}
}

type Dialect struct {
	schema.BaseDialect

	tables   *schema.Tables
	features feature.Feature
}

func New(opts ...DialectOption) *Dialect {
	d := new(Dialect)
	d.tables = schema.NewTables(d)
	d.features = feature.CTE |
		feature.WithValues |
		feature.Returning |
		//feature.InsertReturning | // TODO
		//feature.Output | // TODO
		feature.InsertOnConflict |
		feature.TableTruncate |
		feature.TableNotExists |
		feature.SelectExists |
		feature.AutoIncrement |
		feature.CompositeIn |
		feature.DeleteReturning

	for _, opt := range opts {
		opt(d)
	}

	return d
}

type DialectOption func(d *Dialect)

func WithoutFeature(other feature.Feature) DialectOption {
	return func(d *Dialect) {
		d.features = d.features.Remove(other)
	}
}

func (d *Dialect) Init(*sql.DB) {}

func (d *Dialect) Name() dialect.Name {
	return dialect.Oracle
}

func (d *Dialect) Features() feature.Feature {
	return d.features
}

func (d *Dialect) Tables() *schema.Tables {
	return d.tables
}

func (d *Dialect) OnTable(table *schema.Table) {
	for _, field := range table.FieldMap {
		d.onField(field)
	}
}

func (d *Dialect) onField(field *schema.Field) {
	field.DiscoveredSQLType = fieldSQLType(field)
}

func (d *Dialect) IdentQuote() byte {
	return '"'
}

func (*Dialect) AppendBytes(b, bs []byte) []byte {
	if bs == nil {
		return dialect.AppendNull(b)
	}

	b = append(b, "0x"...)

	s := len(b)
	b = append(b, make([]byte, hex.EncodedLen(len(bs)))...)
	hex.Encode(b[s:], bs)

	return b
}

func (d *Dialect) DefaultVarcharLen() int {
	return 255
}

func (d *Dialect) DefaultSchema() string {
	return "app"
}

func (d *Dialect) AppendSequence(b []byte, table *schema.Table, field *schema.Field) []byte {
	return append(b, " GENERATED BY DEFAULT AS IDENTITY"...)
}

func fieldSQLType(field *schema.Field) string {
	switch field.DiscoveredSQLType {
	case sqltype.SmallInt, sqltype.BigInt:
		// INTEGER PRIMARY KEY is an alias for the ROWID.
		// It is safe to convert all ints to INTEGER, because SQLite types don't have size.
		return sqltype.Integer
	case sqltype.Boolean:
		return "number(1,0)"
	default:
		return field.DiscoveredSQLType
	}
}

func (*Dialect) AppendTime(b []byte, tm time.Time) []byte {
	if tm.IsZero() {
		b = append(b, "NULL"...)
		return b
	}
	b = append(b, "TO_TIMESTAMP('"...)
	b = tm.AppendFormat(b, "2006-01-02 15:04:05.999999")
	b = append(b, "', 'YYYY-MM-DD HH24:MI:SS.FF')"...)
	return b
}

func (*Dialect) AppendBool(b []byte, v bool) []byte {
	if v {
		return append(b, '1')
	}

	return append(b, '0')
}
